name: Publish docs via GitHub Pages
on:
  push:
    branches:
      - main

jobs:
  build:
    name: Deploy docs
    runs-on: ubuntu-latest
    steps:
      - name: Setup environment
        uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: docs_gen
          channels: defaults,conda-forge
          environment-file: docs_gen.yml
          auto-update-conda: true
          auto-activate-base: false

      - name: Install mkdocs themes
        shell: bash -l {0}
        run: |
          pip install mkdocs-bootstrap
          pip install mkdocs-bootstrap-tables-plugin
          pip install mkdocs-mermaid2-plugin

      - name: Checkout gh-pages
        uses: actions/checkout@v2

      - name: Deploy docs
        uses: mhausenblas/mkdocs-deploy-gh-pages@master
        # Or use mhausenblas/mkdocs-deploy-gh-pages@nomaterial to build without the mkdocs-material theme
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CUSTOM_DOMAIN: docs.riskdatalibrary.org
          CONFIG_FILE: mkdocs.yml
          EXTRA_PACKAGES: build-base, search, bootstrap-tables, mermaid2
          # GITHUB_DOMAIN: github.myenterprise.com
