name: Publish docs via GitHub Pages
on:
  push:
    branches:
      - gh-pages

jobs:
  build:
    name: Deploy docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout gh-pages
        uses: actions/checkout@v2

      - name: Deploy docs
        uses: mhausenblas/mkdocs-deploy-gh-pages@master
        # Or use mhausenblas/mkdocs-deploy-gh-pages@nomaterial to build without the mkdocs-material theme
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CUSTOM_DOMAIN: docs.riskdatalibrary.org
          CONFIG_FILE: mkdocs.yml
          EXTRA_PACKAGES: build-base, search, bootstrap-tables, mermaid2
          # GITHUB_DOMAIN: github.myenterprise.com
